bootstrap:
    goagen bootstrap -d bitbucket.org/james2doyle/geo-gambler/server/design
js:
    goagen js -d bitbucket.org/james2doyle/geo-gambler/server/design

app:
    goagen app -d bitbucket.org/james2doyle/geo-gambler/server/design

clean:
    rm -rf app